INSERT INTO extended
SELECT * FROM com
WHERE id='9336';
DELETE FROM com WHERE id='9336';
INSERT INTO extended
SELECT * FROM com
WHERE id='11016';
DELETE FROM com WHERE id='11016';
INSERT INTO extended
SELECT * FROM com
WHERE id='4719';
DELETE FROM com WHERE id='4719';
INSERT INTO extended
SELECT * FROM com
WHERE id='8935';
DELETE FROM com WHERE id='8935';
INSERT INTO extended
SELECT * FROM com
WHERE id='6353';
DELETE FROM com WHERE id='6353';
INSERT INTO extended
SELECT * FROM com
WHERE id='6973';
DELETE FROM com WHERE id='6973';
INSERT INTO extended
SELECT * FROM com
WHERE id='12195';
DELETE FROM com WHERE id='12195';
INSERT INTO extended
SELECT * FROM com
WHERE id='10844';
DELETE FROM com WHERE id='10844';
INSERT INTO extended
SELECT * FROM com
WHERE id='4521';
DELETE FROM com WHERE id='4521';
INSERT INTO extended
SELECT * FROM com
WHERE id='4164';
DELETE FROM com WHERE id='4164';
INSERT INTO extended
SELECT * FROM com
WHERE id='6244';
DELETE FROM com WHERE id='6244';
INSERT INTO extended
SELECT * FROM com
WHERE id='10360';
DELETE FROM com WHERE id='10360';
INSERT INTO extended
SELECT * FROM com
WHERE id='5023';
DELETE FROM com WHERE id='5023';
INSERT INTO extended
SELECT * FROM com
WHERE id='7943';
DELETE FROM com WHERE id='7943';
INSERT INTO extended
SELECT * FROM com
WHERE id='3798';
DELETE FROM com WHERE id='3798';
INSERT INTO extended
SELECT * FROM com
WHERE id='11071';
DELETE FROM com WHERE id='11071';
INSERT INTO extended
SELECT * FROM com
WHERE id='7257';
DELETE FROM com WHERE id='7257';
INSERT INTO extended
SELECT * FROM com
WHERE id='4062';
DELETE FROM com WHERE id='4062';
INSERT INTO extended
SELECT * FROM com
WHERE id='67979';
DELETE FROM com WHERE id='67979';
INSERT INTO extended
SELECT * FROM com
WHERE id='6257';
DELETE FROM com WHERE id='6257';
INSERT INTO extended
SELECT * FROM com
WHERE id='7391';
DELETE FROM com WHERE id='7391';
INSERT INTO extended
SELECT * FROM com
WHERE id='7281';
DELETE FROM com WHERE id='7281';
INSERT INTO extended
SELECT * FROM com
WHERE id='4053';
DELETE FROM com WHERE id='4053';