CREATE TABLE extended
(id varchar(5) PRIMARY KEY,
kingdom varchar(8),
phylum varchar(10),
class_ varchar(14),
order_ varchar(17),
family varchar(17),
genus varchar(17),
species varchar(29),
subspecies varchar(13),
scientific_name varchar(40),
author varchar(70),
rank_ varchar(10),
listing varchar(7),
party varchar(5),
listed_under varchar(33),
full_note varchar(3458),
full_note_ varchar(11),
all_distributionfullnames varchar(2615),
all_distributionisocodes varchar(626),
nativedistributionfullnames varchar(2518),
introduced_distribution varchar(428),
introduced_p_distribution varchar(26),
reintroduced_distribution varchar(73),
extinct_distribution varchar(263),
extinct_p_distribution varchar(54),
distribution_uncertain varchar(289));